# Generated by Django 3.1.6 on 2024-08-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telephone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
